name: flutter_demo
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  overlay_support: ^0.0.3 #Toast
  dio: ^2.0.0 #dio

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
